spring:
  datasource:
    url: jdbc:postgresql://dpg-d6p42f6a2pns73f614og-a:5432/intrusion_detection_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  main:
    allow-bean-definition-overriding: true
